// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAnifc1L82TIUEzLCEbu5ZCJcpYtW4bg0',
    appId: '1:972327809184:web:88c43ceb80a506b7f519c5',
    messagingSenderId: '972327809184',
    projectId: 'mynotes-mya210409',
    authDomain: 'mynotes-mya210409.firebaseapp.com',
    storageBucket: 'mynotes-mya210409.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD3JAJOX3TTb8teKgUxevtEWEJU_lvFXY',
    appId: '1:972327809184:android:3177521cee5ef3c5f519c5',
    messagingSenderId: '972327809184',
    projectId: 'mynotes-mya210409',
    storageBucket: 'mynotes-mya210409.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAnifc1L82TIUEzLCEbu5ZCJcpYtW4bg0',
    appId: '1:972327809184:web:2f11b2b466773edff519c5',
    messagingSenderId: '972327809184',
    projectId: 'mynotes-mya210409',
    authDomain: 'mynotes-mya210409.firebaseapp.com',
    storageBucket: 'mynotes-mya210409.firebasestorage.app',
  );
}
